name: UMI
favicon: null
layout_spectrum: 0.00181
typography_spectrum: 0.37846
title: The Ultimate Mediator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#424242'
    - '#040404'
    - '#ffffff'
    - '#0072b9'
    - '#868686'
  brandStrength: 0.25
  lightness: 0.21914228494279087
  saturation: 0.35942662111483514
  rhythmicContrast: 0.756943613756448
purpose: []
